services:
  mongodb:
    image: mongo:7.0.14
    container_name: task-manager-mongodb
    restart: always
    ports:
      - "27017:27017"  # Map host port 27017 to container port 27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: task-manager-db
    volumes:
      - mongodb-data:/data/db

  backend:
    build:
      context: ./backend  # Path to the backend Dockerfile
    image: task-manager-backend:latest
    container_name: task-manager-backend
    ports:
      - "9090:9090"  # Map host port 9090 to container port 9090
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://root:example@mongodb:27017/task-manager-db

  frontend:
    build:
      context: ./frontend  # Path to the frontend Dockerfile
    image: task-manager-frontend:latest
    container_name: task-manager-frontend
    ports:
      - "3000:3000"  # Map host port 3000 to container port 3000
    depends_on:
      - backend  # Start the backend service before the frontend service

volumes:
  mongodb-data: